### PR TITLE
button: add classname prop

### PR DESCRIPTION
**Pull request by vcapretz**
just an additional prop so the button can receive an external classname
(like the input already does)

### CODE REVIEW

**Comment by derekstavis** [comment]
What's the context for this change? By design we didn't add `className` prop in button. The rationale is that buttons shouldn't receive any external modification to avoid slightly different buttons in some places, making them consistent. If there is an use case we should handle in button, it should be added to it, not via external `className`.

**Comment by vcapretz** [comment]
hey @derekstavis, I totally understand that! 

but we are creating a page which has some buttons that should indeed be totally different than the other ones, see: 

screen shot 2018-05-03 at 10 27 23

they are bigger and they should behave differently from the other ones, and actually, we are now using more than just a simple String as children and I saw on former-kit that the only accepted PropType is string, do you think we can solve it differently?

**Comment by derekstavis** [comment]
Thanks for the explanation! In my view, it should be implemented as a custom button inside your project. The ideia of FormerKit's `Button` is to be a simple button with an optional icon, nothing more :)

**Comment by vcapretz** [comment]
ok!

**Pull request closed without merging**
