### PR TITLE
[EXP-659] Bump React to 17.0.2 

### PR DESCRIPTION
**Pull request by Hrfreire**
## Context
Atualiza para React 17, removendo as funções de ciclo de vida do componente que estavam depreciadas . A única função que não foi removida, foi `componentWillReceiveProps` que foi renomeada para a versão UNSAFE. Será necessário refatorar alguns componentes para remover essa função, e isso será feito em uma issue separada.

## Checklist
- [x] Atualiza o React e o React-DOM para 17.0.2
- [x] Renomeia `componentWillReceiveProps` para `UNSAFE_componentWillReceiveProps` 
- [x] Remove uso de `componentWillMount`

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 62e1ff72b2f038ee69f850c26c40189a89635786
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 62e1ff72b2f038ee69f850c26c40189a89635786
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by diegodsgarcia — CHANGES_REQUESTED** [review]
Faltou apenas mudar a versão do pacote para 2.10.1, para conseguirmos publicar no npm. De resto ta show :100:

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 62e1ff72b2f038ee69f850c26c40189a89635786
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 62e1ff72b2f038ee69f850c26c40189a89635786
  * Always use the standard `scope: action description`, always in english  
    - The **scope** shouldn't have spaces. If the word is composite, use dashes.  
    - The **action** should be **add**, **remove**, **refactor**, **move**,  **bump**, **update** or **release**  
    - The **description** should contain a quick description of the change

The complete commit style guide is available at https://github.com/pagarme/git-style-guide

---
This message was auto-generated by https://gitcop.com

**Review by diegodsgarcia — APPROVED** [review]

**Review by vagnervst — APPROVED** [review]

**Pull request merged**
